services:
  app:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    container_name: allchess-app-local
    env_file:
      - .env
    environment:
      DEPLOYMENT_TARGET: local
      DATABASE_DRIVER: d1
      OBJECT_STORAGE_DRIVER: r2
    ports:
      - "3000:3000"
