import type { VariantDefinition } from "./types";

export const variantCatalog: VariantDefinition[] = [
  {
    key: "classic",
    nameKey: "variant.classic",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "Checkmate the opponent king.",
    startFen: "start",
    setup: ["rnbqkbnr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNBQKBNR"],
    aliases: ["standard", "fide"]
  },
  {
    key: "chaturanga",
    nameKey: "variant.chaturanga",
    rulesAdapter: "chessops",
    engineProtocol: "internal",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate or bare the opposing king using the ancient four-division army.",
    setup: ["rnekmenr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNEKMENR"],
    aliases: ["ancient-indian-chess"]
  },
  {
    key: "crazyhouse",
    nameKey: "variant.crazyhouse",
    rulesAdapter: "chessops",
    engineProtocol: "internal",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: true,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "Checkmate with captured pieces dropped back from each player's pocket.",
    setup: ["rnbqkbnr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNBQKBNR"],
    aliases: ["drop-chess"]
  },
  {
    key: "shatranj",
    nameKey: "variant.shatranj",
    rulesAdapter: "chessops",
    engineProtocol: "internal",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate or bare the opposing king using ferz and alfil movement.",
    setup: ["rnakfanr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNAFKANR"],
    aliases: ["persian-chess"]
  },
  {
    key: "chess960",
    nameKey: "variant.chess960",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "Checkmate with randomized back ranks.",
    setup: ["nrkbqrbn", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "NRKBQRBN"],
    aliases: ["fischer-random"]
  },
  {
    key: "xiangqi",
    nameKey: "variant.xiangqi",
    rulesAdapter: "xiangqiops",
    engineProtocol: "uci",
    family: "east-asian",
    board: { rows: 10, cols: 9, coordinates: "xiangqi" },
    players: ["red", "black"],
    supportsDrops: false,
    supportsPromotion: false,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate or stalemate the opposing general.",
    setup: ["rheagaehr", ".........", ".c.....c.", "p.p.p.p.p", ".........", ".........", "P.P.P.P.P", ".C.....C.", ".........", "RHEAGAEHR"],
    aliases: ["chinese-chess"]
  },
  {
    key: "shogi",
    nameKey: "variant.shogi",
    rulesAdapter: "shogiops",
    engineProtocol: "usi",
    family: "east-asian",
    board: { rows: 9, cols: 9, coordinates: "shogi" },
    players: ["sente", "gote"],
    supportsDrops: true,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate the opposing king using moves, drops, and promotions.",
    setup: ["lnsgkgsnl", ".r.....b.", "ppppppppp", ".........", ".........", ".........", "PPPPPPPPP", ".B.....R.", "LNSGKGSNL"],
    aliases: ["japanese-chess"]
  },
  {
    key: "mini-shogi",
    nameKey: "variant.mini-shogi",
    rulesAdapter: "shogiops",
    engineProtocol: "internal",
    family: "east-asian",
    board: { rows: 5, cols: 5, coordinates: "shogi" },
    players: ["sente", "gote"],
    supportsDrops: true,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate on a 5x5 Shogi board with drops and a one-rank promotion zone.",
    setup: ["rbsgk", "....p", ".....", "P....", "KGSBR"],
    aliases: ["minishogi", "gogo-shogi", "5x5-shogi"]
  },
  {
    key: "janggi",
    nameKey: "variant.janggi",
    rulesAdapter: "allchess-janggi",
    engineProtocol: "internal",
    family: "east-asian",
    board: { rows: 10, cols: 9, coordinates: "xiangqi" },
    players: ["red", "blue"],
    supportsDrops: false,
    supportsPromotion: false,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate the opposing general on a palace board.",
    setup: ["rheagaehr", ".........", ".c.....c.", "p.p.p.p.p", ".........", ".........", "P.P.P.P.P", ".C.....C.", ".........", "RHEAGAEHR"],
    aliases: ["korean-chess"]
  },
  {
    key: "makruk",
    nameKey: "variant.makruk",
    rulesAdapter: "makruk-js",
    engineProtocol: "uci",
    family: "southeast-asian",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Checkmate with Thai chess movement and promotion rules.",
    setup: ["rnsmksnr", "........", "pppppppp", "........", "........", "PPPPPPPP", "........", "RNSMKSNR"],
    aliases: ["thai-chess"]
  },
  {
    key: "jungle",
    nameKey: "variant.jungle",
    rulesAdapter: "allchess-jungle",
    engineProtocol: "internal",
    family: "abstract",
    board: { rows: 9, cols: 7, coordinates: "jungle" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: false,
    supportsCastling: false,
    supportsCheck: false,
    objective: "Enter the opponent den or capture all animals.",
    setup: ["l.....t", ".d...c.", "r.p.w.e", ".......", ".......", ".......", "E.W.P.R", ".C...D.", "T.....L"],
    aliases: ["dou-shou-qi"]
  },
  {
    key: "english-draughts",
    nameKey: "variant.english-draughts",
    rulesAdapter: "draughts-engine",
    engineProtocol: "internal",
    family: "draughts",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: false,
    objective: "Capture or block every opposing checker with compulsory diagonal jumps.",
    setup: [".p.p.p.p", "p.p.p.p.", ".p.p.p.p", "........", "........", "P.P.P.P.", ".P.P.P.P", "P.P.P.P."],
    aliases: ["checkers", "american-checkers", "english-checkers"]
  },
  {
    key: "international-draughts",
    nameKey: "variant.international-draughts",
    rulesAdapter: "draughts-engine",
    engineProtocol: "internal",
    family: "draughts",
    board: { rows: 10, cols: 10, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: false,
    objective: "Capture or block every opposing checker on a 10x10 board with maximum-capture rules.",
    setup: [".p.p.p.p.p", "p.p.p.p.p.", ".p.p.p.p.p", "p.p.p.p.p.", "..........", "..........", ".P.P.P.P.P", "P.P.P.P.P.", ".P.P.P.P.P", "P.P.P.P.P."],
    aliases: ["polish-draughts", "international-checkers", "10x10-draughts"]
  },
  {
    key: "antichess",
    nameKey: "variant.antichess",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: false,
    supportsCheck: false,
    objective: "Lose all pieces; captures are compulsory.",
    setup: ["rnbqkbnr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNBQKBNR"],
    aliases: ["giveaway"]
  },
  {
    key: "horde",
    nameKey: "variant.horde",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "The horde tries to overwhelm the standard army.",
    setup: ["rnbqkbnr", "pppppppp", "........", "PPPPPPPP", "PPPPPPPP", "PPPPPPPP", "PPPPPPPP", "........"],
    aliases: []
  },
  {
    key: "king-of-the-hill",
    nameKey: "variant.king-of-the-hill",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "Checkmate or bring the king to a center square.",
    setup: ["rnbqkbnr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNBQKBNR"],
    aliases: ["koth"]
  },
  {
    key: "three-check",
    nameKey: "variant.three-check",
    rulesAdapter: "chessops",
    engineProtocol: "uci",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: true,
    supportsCastling: true,
    supportsCheck: true,
    objective: "Checkmate or deliver three checks.",
    setup: ["rnbqkbnr", "pppppppp", "........", "........", "........", "........", "PPPPPPPP", "RNBQKBNR"],
    aliases: ["3-check"]
  },
  {
    key: "racing-kings",
    nameKey: "variant.racing-kings",
    rulesAdapter: "chessops",
    engineProtocol: "internal",
    family: "western",
    board: { rows: 8, cols: 8, coordinates: "orthodox" },
    players: ["white", "black"],
    supportsDrops: false,
    supportsPromotion: false,
    supportsCastling: false,
    supportsCheck: true,
    objective: "Race the king to the eighth rank without giving check.",
    setup: ["........", "........", "........", "........", "........", "........", "krbnNBRK", "qrbnNBRQ"],
    aliases: ["racing"]
  }
] satisfies VariantDefinition[];

export type VariantKey = (typeof variantCatalog)[number]["key"];

export function getVariant(key: string): VariantDefinition {
  const found = variantCatalog.find((variant) => variant.key === key || variant.aliases.includes(key));
  if (!found) {
    throw new Error(`Unknown variant: ${key}`);
  }
  return found;
}
